# device
accelerator: cpu
devices: 1
num_nodes: 0
# limits
max_epochs: 2
log_every_n_steps: 1
check_val_every_n_epoch: 1
# tracking & debugging
track_grad_norm: inf
# logging & checkpointing
logger: true
enable_checkpointing: true
