# lightning.pytorch==1.8.6
seed_everything: true
trainer:
  max_epochs: 10
  accelerator: gpu
  devices: 1
  num_nodes: 0
  log_every_n_steps: 1
  track_grad_norm: inf
  logger: true
  enable_checkpointing: true
  check_val_every_n_epoch: 1
model:
  base_distribution: normflows.distributions.DiagGaussian
  base_distribution_args: 
    shape: 3
    trainable: False
  in_features: 3
  layers: [3, 3]
  num_transforms: 3
  additive: False
  elementwise_perm: True
  use_soft_on_maximization: True
  # (1) Use fixed permutations
  ordering: [0, 2, 1]
    
  learn_permutation: False
  optimizer: torch.optim.AdamW
  residual: false
  bias: true
  activation: torch.nn.LeakyReLU
  activation_args: null
  batch_norm: false
  batch_norm_args: null
  additive: false
  num_transforms: 1
  ordering: null
  learn_permutation: true
  log_input_outputs: false
  device: null
  dtype: null
  starting_phase: maximization
  use_soft_on_maximization: true
  phase_change_upper_bound: 100
  expectation_epoch_upper_bound: 10000
  expectation_epoch_lower_bound: 10
  maximization_epoch_upper_bound: 10000
  maximization_epoch_lower_bound: 10
  overfit_window_size: 10
  overfit_check_threshold: 0.05
  overfitting_patience: 3
  criterion_args: null
  optimizer: torch.optim.Adam
  optimizer_is_active: null
  optimizer_parameters: null
  optimizer_args: null
  lr: 0.0001
  scheduler: null
  scheduler_name: null
  scheduler_optimizer: null
  scheduler_args: null
  scheduler_interval: epoch
  scheduler_frequency: 1
  scheduler_monitor: null
data:
  seed: 100
  observation_size: 10000
  batch_size: 128
  num_workers: 4  # set to 0 for no multiprocessing
  scm_generator_class: ocd.data.affine_additive.scm.AffineAdditiveSCMGenerator
  scm_generator_args: 
    graph_generator_type: chain
    graph_generator_args: 
      n: 3
    function_type: linear_affine_with_exp_modulatd
    noise_type: gaussian
    functional_form_generator_args:
      weight_low: 0.5
      weight_high: 20
      noise_std_low: 1.0
      noise_std_high: 1.0
      noise_mean_low: 0.0
      noise_mean_high: 0.0
  val_size: 0.1
  interventional_episode_count: null
  interventional_episode_size: null
  intervention_function: null
  dl_args: null
  train_dl_args: null
  val_dl_args: null
  train_batch_size: null
  val_batch_size: null
  pin_memory: true
  train_pin_memory: null
  val_pin_memory: null
  train_shuffle: true
  val_shuffle: false
  num_workers: 0
  train_num_workers: null
  val_num_workers: null
ckpt_path: null
